# Generated by Django 6.0.3 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_plugin_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='plugin',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
